# RDI Server Configuration
# This configuration file defines how RDI server connects to Redis for metadata storage

# Redis connection for RDI metadata storage
redis:
  host: 3.148.243.197
  port: 13000
  username: default
  password: redislabs
  ssl: false
  timeout: 5000
  database: 0  # Database index for RDI metadata
  
# RDI Server settings
server:
  port: 8080
  host: 0.0.0.0
  ssl:
    enabled: false
    port: 9443
    keystore: /opt/rdi/ssl/keystore.jks
    keystore_password: changeit
    
# API settings
api:
  enabled: true
  cors:
    enabled: true
    allowed_origins: "*"
    allowed_methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed_headers: "*"

# Logging configuration
logging:
  level: INFO
  file: /opt/rdi/logs/rdi-server.log
  max_file_size: 100MB
  max_files: 10
  console: true

# Pipeline management
pipeline:
  config_dir: /opt/rdi/pipeline-config
  jobs_dir: /opt/rdi/pipeline-config/jobs
  auto_reload: true
  validation: true

# Monitoring and metrics
monitoring:
  enabled: true
  metrics:
    enabled: true
    port: 9090
    path: /metrics
  health_check:
    enabled: true
    path: /health
    
# Security settings
security:
  authentication:
    enabled: false  # Set to true in production
    type: basic     # basic, jwt, oauth2
  authorization:
    enabled: false

# Performance tuning
performance:
  thread_pool_size: 10
  connection_pool_size: 20
  max_memory_usage: 512MB
  
# Data processing settings
processing:
  batch_size: 1000
  flush_interval: 5000  # milliseconds
  retry_attempts: 3
  retry_delay: 1000     # milliseconds
